version: "3.8"

services:
  n8n:
    image: n8nio/n8n:1.27.0         # pin a stable version
    restart: unless-stopped
    ports:
      - "5678:5678"                 # HOST:CONTAINER
    environment:
      - TZ=Europe/London           # your local timezone
      # ─── Basic Auth (highly recommended) ───
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin18
      # ─── Webhook + URL settings ───
      - WEBHOOK_URL=http://localhost:5678
      # ─── Telemetry off (optional) ───
      - N8N_DIAGNOSTICS_ENABLED=false
    volumes:
      - n8n_data:/home/node/.n8n   # persist workflows & credentials

volumes:
  n8n_data:
